# Docker Compose file Reference (https://github.com/compose-spec/compose-spec/blob/master/03-compose-file.md)
version: '3'

services:

  db:
    image: "postgres:9.6-alpine"
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

  # Back-end Spring Boot Application
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - db
    ports:
      - 8080:808

  # Front-end Angular Application
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 4200:80
    depends_on: 
      - backend

